name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/ping-bot
            git pull origin main

            /home/ubuntu/.nvm/versions/node/v24.14.1/bin/npm install

            /home/ubuntu/.nvm/versions/node/v24.14.1/bin/pm2 restart ping-bot